site_name: MarketWatchData Docs
theme: material
nav:
  - home: index.md  
  - marketwatchdata: marketwatchdata.md

plugins:
  - mkdocstrings: 
      watch:
        - marketwatchdata
  - search:
watch:
  - .  # reload docs for any file changes