site_name: MarketWatchData Docs
# theme: material
theme: 
  name: material
  features:
    - content.code.select
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - home: index.md  
  - marketwatchdata: marketwatchdata.md

plugins:
  - mkdocstrings: 
      watch:
        - marketwatchdata
  - search:
watch:
  - .  # reload docs for any file changes